### ISSUE TITLE
Fix default next param value

### ISSUE THREAD

**Issue by marksteve** [insynchq/flask-googlelogin#3]

**Comment by joshkendrick** [comment]
@marksteve is this the issue where if the user tries to go a @login_required view without first being logged in and not having accepted the permissions before, they'll get into be continuously redirected between oauth2callback and the @login_required view they were trying to access?

Just asking because it's an issue i've run into today, and ive been trying to solve it but havent made any progress. i was going to report it, but it looks like this might be the same issue.

**Comment by marksteve** [comment]
@joshkendrick Sorry for the late reply. This issue is more about filtering the next param for security (i.e. some might make use of the next param to redirect users to a phishing site after login).

**Comment by joshkendrick** [comment]
@marksteve gotcha. I'll report this other issue I was seeing separately.
